let
    Origen = Folder.Files(#"RUTA (2)"),
    #"Filas filtradas" = Table.SelectRows(Origen, each not Text.StartsWith([Extension], "~")),
    #"Filas filtradas1" = Table.SelectRows(#"Filas filtradas", each ([Extension] = ".xlsx") and ([Name] = "PIB_Corriente_Brasil.xlsx")),
    #"Otras columnas quitadas" = Table.SelectColumns(#"Filas filtradas1",{"Content", "Name"}),
    #"Personalizada agregada" = Table.AddColumn(#"Otras columnas quitadas", "Personalizado", each Excel.Workbook([Content],true)),
    #"Otras columnas quitadas1" = Table.SelectColumns(#"Personalizada agregada",{"Personalizado"}),
    #"Se expandió Personalizado" = Table.ExpandTableColumn(#"Otras columnas quitadas1", "Personalizado", {"Name", "Data", "Item", "Kind", "Hidden"}, {"Name", "Data", "Item", "Kind", "Hidden"}),
    #"Otras columnas quitadas2" = Table.SelectColumns(#"Se expandió Personalizado",{"Data"}),
    #"Se expandió Data" = Table.ExpandTableColumn(#"Otras columnas quitadas2", "Data", {"Tabela 1846 - Valores a preços correntes", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68", "Column69", "Column70", "Column71", "Column72", "Column73", "Column74", "Column75", "Column76", "Column77", "Column78", "Column79", "Column80", "Column81", "Column82", "Column83", "Column84", "Column85", "Column86", "Column87", "Column88", "Column89", "Column90", "Column91", "Column92", "Column93", "Column94", "Column95", "Column96", "Column97", "Column98", "Column99", "Column100", "Column101", "Column102", "Column103", "Column104", "Column105", "Column106", "Column107", "Column108", "Column109", "Column110", "Column111", "Column112", "Column113", "Column114", "Column115"}, {"Tabela 1846 - Valores a preços correntes", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68", "Column69", "Column70", "Column71", "Column72", "Column73", "Column74", "Column75", "Column76", "Column77", "Column78", "Column79", "Column80", "Column81", "Column82", "Column83", "Column84", "Column85", "Column86", "Column87", "Column88", "Column89", "Column90", "Column91", "Column92", "Column93", "Column94", "Column95", "Column96", "Column97", "Column98", "Column99", "Column100", "Column101", "Column102", "Column103", "Column104", "Column105", "Column106", "Column107", "Column108", "Column109", "Column110", "Column111", "Column112", "Column113", "Column114", "Column115"}),
    #"Filas filtradas2" = Table.SelectRows(#"Se expandió Data", each ([Column3] <> null)),
    #"Tabla transpuesta" = Table.Transpose(#"Filas filtradas2"),
    #"Encabezados promovidos" = Table.PromoteHeaders(#"Tabla transpuesta", [PromoteAllScalars=true]),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Column1", type text}, {"Agropecuária - total", Int64.Type}, {"Indústria - total", Int64.Type}, {"Indústrias extrativas", Int64.Type}, {"Indústrias de transformação", Int64.Type}, {"Eletricidade e gás, água, esgoto, atividades de gestão de resíduos", Int64.Type}, {"Construção", Int64.Type}, {"Serviços - total", Int64.Type}, {"Comércio", Int64.Type}, {"Transporte, armazenagem e correio", Int64.Type}, {"Informação e comunicação", Int64.Type}, {"Atividades financeiras, de seguros e serviços relacionados", Int64.Type}, {"Atividades imobiliárias", Int64.Type}, {"Outras atividades de serviços", Int64.Type}, {"Administração, saúde e educação públicas e seguridade social", Int64.Type}, {"Valor adicionado a preços básicos", Int64.Type}, {"Impostos líquidos sobre produtos", Int64.Type}, {"PIB a preços de mercado", Int64.Type}, {"Despesa de consumo das famílias", Int64.Type}, {"Despesa de consumo da administração pública", Int64.Type}, {"Formação bruta de capital fixo", Int64.Type}, {"Variação de estoque", Int64.Type}, {"Exportação de bens e serviços", Int64.Type}, {"Importação de bens e serviços (-)", Int64.Type}}),
    #"Dividir columna por posición" = Table.SplitColumn(#"Tipo cambiado", "Column1", Splitter.SplitTextByPositions({0, 13}, false), {"Column1.1", "Column1.2"}),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Dividir columna por posición",{{"Column1.1", type text}, {"Column1.2", Int64.Type}}),
    #"Otras columnas con anulación de dinamización" = Table.UnpivotOtherColumns(#"Tipo cambiado1", {"Column1.1", "Column1.2"}, "Atributo", "Valor"),
    #"Personalizada agregada1" = Table.AddColumn(#"Otras columnas con anulación de dinamización", "Trimestre", each if [Column1.1] = "1º trimestre " then "I" else if [Column1.1] = "2º trimestre " then "II" else if [Column1.1] = "3º trimestre " then "III" else if [Column1.1] = "4º trimestre " then "IV" else ""),
    #"Columnas quitadas" = Table.RemoveColumns(#"Personalizada agregada1",{"Column1.1"}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas quitadas",{{"Column1.2", "Año"}, {"Atributo", "Concepto"}}),
    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Trimestre", type text}}),
    #"Personalizada agregada2" = Table.AddColumn(#"Tipo cambiado2", "País", each "Brasil")
in
    #"Personalizada agregada2"
