let
    Origen = Folder.Files(#"RUTA (4)"),
    #"Filas filtradas1" = Table.SelectRows(Origen, each not Text.StartsWith([Extension], "~")),
    #"Filas filtradas" = Table.SelectRows(#"Filas filtradas1", each ([Extension] = ".xlsx") and ([Name] = "PIBT_3_Mexico.xlsx")),
    #"Otras columnas quitadas" = Table.SelectColumns(#"Filas filtradas",{"Content", "Name"}),
    #"Personalizada agregada" = Table.AddColumn(#"Otras columnas quitadas", "Personalizado", each Excel.Workbook([Content],true)),
    #"Otras columnas quitadas1" = Table.SelectColumns(#"Personalizada agregada",{"Personalizado"}),
    #"Se expandió Personalizado" = Table.ExpandTableColumn(#"Otras columnas quitadas1", "Personalizado", {"Name", "Data", "Item", "Kind", "Hidden"}, {"Name", "Data", "Item", "Kind", "Hidden"}),
    #"Filas filtradas2" = Table.SelectRows(#"Se expandió Personalizado", each ([Name] = "Tabulado")),
    #"Otras columnas quitadas2" = Table.SelectColumns(#"Filas filtradas2",{"Data"}),
    #"Se expandió Data" = Table.ExpandTableColumn(#"Otras columnas quitadas2", "Data", {"Instituto Nacional de Estadística y Geografía (INEGI).", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68", "Column69", "Column70", "Column71", "Column72", "Column73", "Column74", "Column75", "Column76", "Column77", "Column78", "Column79", "Column80", "Column81", "Column82", "Column83", "Column84", "Column85", "Column86", "Column87", "Column88", "Column89", "Column90", "Column91", "Column92", "Column93", "Column94", "Column95", "Column96", "Column97", "Column98", "Column99", "Column100", "Column101", "Column102", "Column103", "Column104", "Column105", "Column106", "Column107", "Column108", "Column109", "Column110", "Column111", "Column112", "Column113", "Column114", "Column115", "Column116", "Column117", "Column118", "Column119", "Column120", "Column121", "Column122", "Column123", "Column124", "Column125", "Column126", "Column127", "Column128", "Column129", "Column130", "Column131", "Column132", "Column133", "Column134", "Column135", "Column136", "Column137", "Column138", "Column139", "Column140", "Column141", "Column142", "Column143", "Column144", "Column145", "Column146", "Column147", "Column148", "Column149", "Column150", "Column151", "Column152", "Column153", "Column154", "Column155", "Column156", "Column157", "Column158", "Column159", "Column160", "Column161", "Column162", "Column163", "Column164", "Column165", "Column166", "Column167", "Column168", "Column169", "Column170", "Column171", "Column172", "Column173", "Column174", "Column175", "Column176", "Column177", "Column178", "Column179", "Column180", "Column181", "Column182", "Column183", "Column184", "Column185", "Column186", "Column187", "Column188", "Column189", "Column190", "Column191", "Column192", "Column193", "Column194", "Column195", "Column196", "Column197", "Column198", "Column199", "Column200", "Column201", "Column202", "Column203", "Column204", "Column205", "Column206", "Column207", "Column208", "Column209", "Column210", "Column211", "Column212", "Column213", "Column214", "Column215", "Column216", "Column217", "Column218", "Column219", "Column220", "Column221", "Column222", "Column223", "Column224", "Column225"}, {"Instituto Nacional de Estadística y Geografía (INEGI).", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68", "Column69", "Column70", "Column71", "Column72", "Column73", "Column74", "Column75", "Column76", "Column77", "Column78", "Column79", "Column80", "Column81", "Column82", "Column83", "Column84", "Column85", "Column86", "Column87", "Column88", "Column89", "Column90", "Column91", "Column92", "Column93", "Column94", "Column95", "Column96", "Column97", "Column98", "Column99", "Column100", "Column101", "Column102", "Column103", "Column104", "Column105", "Column106", "Column107", "Column108", "Column109", "Column110", "Column111", "Column112", "Column113", "Column114", "Column115", "Column116", "Column117", "Column118", "Column119", "Column120", "Column121", "Column122", "Column123", "Column124", "Column125", "Column126", "Column127", "Column128", "Column129", "Column130", "Column131", "Column132", "Column133", "Column134", "Column135", "Column136", "Column137", "Column138", "Column139", "Column140", "Column141", "Column142", "Column143", "Column144", "Column145", "Column146", "Column147", "Column148", "Column149", "Column150", "Column151", "Column152", "Column153", "Column154", "Column155", "Column156", "Column157", "Column158", "Column159", "Column160", "Column161", "Column162", "Column163", "Column164", "Column165", "Column166", "Column167", "Column168", "Column169", "Column170", "Column171", "Column172", "Column173", "Column174", "Column175", "Column176", "Column177", "Column178", "Column179", "Column180", "Column181", "Column182", "Column183", "Column184", "Column185", "Column186", "Column187", "Column188", "Column189", "Column190", "Column191", "Column192", "Column193", "Column194", "Column195", "Column196", "Column197", "Column198", "Column199", "Column200", "Column201", "Column202", "Column203", "Column204", "Column205", "Column206", "Column207", "Column208", "Column209", "Column210", "Column211", "Column212", "Column213", "Column214", "Column215", "Column216", "Column217", "Column218", "Column219", "Column220", "Column221", "Column222", "Column223", "Column224", "Column225"}),
    #"Filas superiores quitadas" = Table.Skip(#"Se expandió Data",3),
    #"Duplicados quitados" = Table.Distinct(#"Filas superiores quitadas", {"Instituto Nacional de Estadística y Geografía (INEGI)."}),
    #"Filas filtradas3" = Table.SelectRows(#"Duplicados quitados", each ([Column2] <> null and [Column2] <> "")),
    #"Tabla transpuesta" = Table.Transpose(#"Filas filtradas3"),
    #"Encabezados promovidos" = Table.PromoteHeaders(#"Tabla transpuesta", [PromoteAllScalars=true]),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Concepto", type text}, {"Column2", type text}, {"____aB.1bP - Producto interno bruto", type number}, {"          D.21-D.31 - Impuestos sobre los productos, netos", type number}, {"____aB.1bV - Valor agregado bruto", type number}, {"          Actividades primarias", type number}, {"               11 - Agricultura, cría y explotación de animales, aprovechamiento forestal, pesca y caza", type number}, {"                    111 - Agricultura", type number}, {"                    112 - Cría y explotación de animales", type number}, {"                    113 - Aprovechamiento forestal", type number}, {"                    114 - Pesca, caza y captura", type number}, {"                    115 - Servicios relacionados con las actividades agropecuarias y forestales", type number}, {"          Actividades secundarias", type number}, {"               21 - Minería", type number}, {"                    211 - Extracción de petróleo y gas", type number}, {"                    212 - Minería de minerales metálicos y no metálicos, excepto petróleo y gas", type number}, {"                    213 - Servicios relacionados con la minería", type number}, {"               22 - Generación, transmisión, distribución y comercialización de energía eléctrica, suministro de agua y de gas natural por ductos al consumidor final", type number}, {"                    221 - Generación, transmisión, distribución y comercialización de energía eléctrica, suministro de agua y de gas natural por ductos al consumidor final", type number}, {"               23 - Construcción", type number}, {"                    236 - Edificación", type number}, {"                    237 - Construcción de obras de ingeniería civil", type number}, {"                    238 - Trabajos especializados para la construcción", type number}, {"               31-33 - Industrias manufactureras", type number}, {"                    311 - Industria alimentaria", type number}, {"                         3111 - Elaboración de alimentos para animales", type number}, {"                         3112 - Molienda de granos y de semillas y obtención de aceites y grasas", type number}, {"                         3113 - Elaboración de azúcares, chocolates, dulces y similares", type number}, {"                         3114 - Conservación de frutas, verduras, guisos y otros alimentos preparados", type number}, {"                         3115 - Elaboración de productos lácteos", type number}, {"                         3116 - Matanza, empacado y procesamiento de carne de ganado, aves y otros animales comestibles", type number}, {"                         3117 - Preparación y envasado de pescados y mariscos", type number}, {"                         3118 - Elaboración de productos de panadería y tortillas", type number}, {"                         3119 - Otras industrias alimentarias", type number}, {"                    312 - Industria de las bebidas y del tabaco", type number}, {"                         3121 - Industria de las bebidas", type number}, {"                         3122 - Industria del tabaco", type number}, {"                    313 - Fabricación de insumos textiles y acabado de textiles", type number}, {"                         3131 - Preparación e hilado de fibras textiles, y fabricación de hilos", type number}, {"                         3132 - Fabricación de telas", type number}, {"                         3133 - Acabado de productos textiles y fabricación de telas recubiertas", type number}, {"                    314 - Fabricación de productos textiles, excepto prendas de vestir", type number}, {"                         3141 - Confección de alfombras, blancos y similares", type number}, {"                         3149 - Fabricación de otros productos textiles, excepto prendas de vestir", type number}, {"                    315 - Fabricación de prendas de vestir", type number}, {"                         3151 - Fabricación de prendas de vestir de tejido de punto", type number}, {"                         3152 - Confección de prendas de vestir", type number}, {"                         3159 - Confección de accesorios de vestir y otras prendas de vestir no clasificados en otra parte", type number}, {"                    316 - Curtido y acabado de cuero y piel, y fabricación de productos de cuero, piel y materiales sucedáneos", type number}, {"                         3161 - Curtido y acabado de cuero y piel", type number}, {"                         3162 - Fabricación de calzado", type number}, {"                         3169 - Fabricación de otros productos de cuero, piel y materiales sucedáneos", type number}, {"                    321 - Industria de la madera", type number}, {"                         3211 - Aserrado y conservación de la madera", type number}, {"                         3212 - Fabricación de laminados y aglutinados de madera", type number}, {"                         3219 - Fabricación de otros productos de madera", type number}, {"                    322 - Industria del papel", type number}, {"                         3221 - Fabricación de pulpa, papel y cartón", type number}, {"                         3222 - Fabricación de productos de cartón y papel", type number}, {"                    323 - Impresión e industrias conexas", type number}, {"                         3231 - Impresión e industrias conexas", type number}, {"                    324 - Fabricación de productos derivados del petróleo y del carbón", type number}, {"                         3241 - Fabricación de productos derivados del petróleo y del carbón", type number}, {"                    325 - Industria química", type number}, {"                         3251 - Fabricación de productos químicos básicos", type number}, {"                         3252 - Fabricación de resinas y hules sintéticos, y fibras químicas", type number}, {"                         3253 - Fabricación de fertilizantes, pesticidas y otros agroquímicos", type number}, {"                         3254 - Fabricación de productos farmacéuticos", type number}, {"                         3255 - Fabricación de pinturas, recubrimientos y adhesivos", type number}, {"                         3256 - Fabricación de jabones, limpiadores y preparaciones de tocador", type number}, {"                         3259 - Fabricación de otros productos químicos", type number}, {"                    326 - Industria del plástico y del hule", type number}, {"                         3261 - Fabricación de productos de plástico", type number}, {"                         3262 - Fabricación de productos de hule", type number}, {"                    327 - Fabricación de productos a base de minerales no metálicos", type number}, {"                         3271 - Fabricación de productos a base de arcillas y minerales refractarios", type number}, {"                         3272 - Fabricación de vidrio y productos de vidrio", type number}, {"                         3273 - Fabricación de cemento y productos de concreto", type number}, {"                         3274 - Fabricación de cal, yeso y productos de yeso", type number}, {"                         3279 - Fabricación de otros productos a base de minerales no metálicos", type number}, {"                    331 - Industrias metálicas básicas", type number}, {"                         3311 - Industria básica del hierro y del acero", type number}, {"                         3312 - Fabricación de productos de hierro y acero", type number}, {"                         3313 - Industria básica del aluminio", type number}, {"                         3314 - Industrias de metales no ferrosos, excepto aluminio", type number}, {"                         3315 - Moldeo por fundición de piezas metálicas", type number}, {"                    332 - Fabricación de productos metálicos", type number}, {"                         3321 - Fabricación de productos metálicos forjados y troquelados", type number}, {"                         3322 - Fabricación de herramientas de mano sin motor y utensilios de cocina metálicos", type number}, {"                         3323 - Fabricación de estructuras metálicas y productos de herrería", type number}, {"                         3324 - Fabricación de calderas, tanques y envases metálicos", type number}, {"                         3325 - Fabricación de herrajes y cerraduras", type number}, {"                         3326 - Fabricación de alambre, productos de alambre y resortes", type number}, {"                         3327 - Maquinado de piezas y fabricación de tornillos", type number}, {"                         3328 - Recubrimientos y terminados metálicos", type number}, {"                         3329 - Fabricación de otros productos metálicos", type number}, {"                    333 - Fabricación de maquinaria y equipo", type number}, {"                         3331 - Fabricación de maquinaria y equipo agropecuario, para la construcción y para la industria extractiva", type number}, {"                         3332 - Fabricación de maquinaria y equipo para las industrias manufactureras, excepto la metalmecánica", type number}, {"                         3333 - Fabricación de maquinaria y equipo para el comercio y los servicios", type number}, {"                         3334 - Fabricación de equipo de aire acondicionado, calefacción, y de refrigeración industrial y comercial", type number}, {"                         3335 - Fabricación de maquinaria y equipo para la industria metalmecánica", type number}, {"                         3336 - Fabricación de motores de combustión interna, turbinas y transmisiones", type number}, {"                         3339 - Fabricación de otra maquinaria y equipo para la industria en general", type number}, {"                    334 - Fabricación de equipo de computación, comunicación, medición y de otros equipos, componentes y accesorios electrónicos", type number}, {"                         3341 - Fabricación de computadoras y equipo periférico", type number}, {"                         3342 - Fabricación de equipo de comunicación", type number}, {"                         3343 - Fabricación de equipo de audio y de video", type number}, {"                         3344 - Fabricación de componentes electrónicos", type number}, {"                         3345 - Fabricación de instrumentos de medición, control, navegación, y equipo médico electrónico", type number}, {"                         3346 - Fabricación y reproducción de medios magnéticos y ópticos", type number}, {"                    335 - Fabricación de accesorios, aparatos eléctricos y equipo de generación de energía eléctrica", type number}, {"                         3351 - Fabricación de accesorios de iluminación", type number}, {"                         3352 - Fabricación de aparatos eléctricos de uso doméstico", type number}, {"                         3353 - Fabricación de equipo de generación y distribución de energía eléctrica", type number}, {"                         3359 - Fabricación de otros equipos y accesorios eléctricos", type number}, {"                    336 - Fabricación de equipo de transporte", type number}, {"                         3361 - Fabricación de automóviles y camiones", type number}, {"                         3362 - Fabricación de carrocerías y remolques", type number}, {"                         3363 - Fabricación de partes para vehículos automotores", type number}, {"                         3364 - Fabricación de equipo aeroespacial", type number}, {"                         3365 - Fabricación de equipo ferroviario", type number}, {"                         3366 - Fabricación de embarcaciones", type number}, {"                         3369 - Fabricación de otro equipo de transporte", type number}, {"                    337 - Fabricación de muebles, colchones y persianas", type number}, {"                         3371 - Fabricación de muebles, excepto de oficina y estantería", type number}, {"                         3372 - Fabricación de muebles de oficina y estantería", type number}, {"                         3379 - Fabricación de colchones, persianas y cortineros", type number}, {"                    339 - Otras industrias manufactureras", type number}, {"                         3391 - Fabricación de equipo no electrónico y material desechable de uso médico, dental y para laboratorio, y artículos oftálmicos", type number}, {"                         3399 - Otras industrias manufactureras", type number}, {"          Actividades terciarias", type number}, {"               43 - Comercio al por mayor", type number}, {"               46 - Comercio al por menor", type number}, {"               48-49 - Transportes, correos y almacenamiento", type number}, {"                    481 - Transporte aéreo", type number}, {"                    482 - Transporte por ferrocarril", type number}, {"                    483 - Transporte por agua", type number}, {"                    484 - Autotransporte de carga", type number}, {"                    485 - Transporte terrestre de pasajeros, excepto por ferrocarril", type number}, {"                    486 - Transporte por ductos", type number}, {"                    487 - Transporte turístico", type number}, {"                    488 - Servicios relacionados con el transporte", type number}, {"                    491 - Servicios postales", type number}, {"                    492 - Servicios de mensajería y paquetería", type number}, {"                    493 - Servicios de almacenamiento", type number}, {"               51 - Información en medios masivos", type number}, {"                    511 - Edición de periódicos, revistas, libros, software y otros materiales, y edición de estas publicaciones integrada con la impresión", type number}, {"                    512 - Industria fílmica y del video, e industria del sonido", type number}, {"                    515 - Radio y televisión", type number}, {"                    517 - Telecomunicaciones", type number}, {"                    518 - Procesamiento electrónico de información, hospedaje y otros servicios relacionados", type number}, {"                    519 - Otros servicios de información", type number}, {"               52 - Servicios financieros y de seguros", type number}, {"                    521 - Banca central", type number}, {"                    522 - Instituciones de intermediación crediticia y financiera no bursátil", type number}, {"                    523 - Actividades bursátiles, cambiarias y de inversión financiera", type number}, {"                    524 - Compañías de seguros, fianzas, y administración de fondos para el retiro", type number}, {"               53 - Servicios inmobiliarios y de alquiler de bienes muebles e intangibles", type number}, {"                    531 - Servicios inmobiliarios", type number}, {"                    532 - Servicios de alquiler de bienes muebles", type number}, {"                    533 - Servicios de alquiler de marcas registradas, patentes y franquicias", type number}, {"               54 - Servicios profesionales, científicos y técnicos", type number}, {"               55 - Corporativos", type number}, {"               56 - Servicios de apoyo a los negocios y manejo de residuos, y servicios de remediación", type number}, {"                    561 - Servicios de apoyo a los negocios", type number}, {"                    562 - Manejo de residuos y servicios de remediación", type number}, {"               61 - Servicios educativos", type number}, {"               62 - Servicios de salud y de asistencia social", type number}, {"                    621 - Servicios médicos de consulta externa y servicios relacionados", type number}, {"                    622 - Hospitales", type number}, {"                    623 - Residencias de asistencia social y para el cuidado de la salud", type number}, {"                    624 - Otros servicios de asistencia social", type number}, {"               71 - Servicios de esparcimiento culturales y deportivos, y otros servicios recreativos", type number}, {"                    711 - Servicios artísticos, culturales y deportivos, y otros servicios relacionados", type number}, {"                    712 - Museos, sitios históricos, zoológicos y similares", type number}, {"                    713 - Servicios de entretenimiento en instalaciones recreativas y otros servicios recreativos", type number}, {"               72 - Servicios de alojamiento temporal y de preparación de alimentos y bebidas", type number}, {"                    721 - Servicios de alojamiento temporal", type number}, {"                    722 - Servicios de preparación de alimentos y bebidas", type number}, {"               81 - Otros servicios excepto actividades gubernamentales", type number}, {"                    811 - Servicios de reparación y mantenimiento", type number}, {"                    812 - Servicios personales", type number}, {"                    813 - Asociaciones y organizaciones", type number}, {"                    814 - Hogares con empleados domésticos", type number}, {"               93 - Actividades legislativas, gubernamentales, de impartición de justicia y de organismos internacionales y extraterritoriales", type number}}),
    #"Filas filtradas4" = Table.SelectRows(#"Tipo cambiado", each ([Column2] <> "6 Meses" and [Column2] <> "9 Meses" and [Column2] <> "Anual")),
    #"Rellenar hacia abajo" = Table.FillDown(#"Filas filtradas4",{"Concepto"}),
    #"Valor reemplazado" = Table.ReplaceValue(#"Rellenar hacia abajo","T1R","T1",Replacer.ReplaceText,{"Column2"}),
    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","T2P","T2",Replacer.ReplaceText,{"Column2"}),
    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","2021P","2021",Replacer.ReplaceText,{"Concepto"}),
    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","2022P","2022",Replacer.ReplaceText,{"Concepto"}),
    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","2023P","2023",Replacer.ReplaceText,{"Concepto"}),
    #"Otras columnas con anulación de dinamización" = Table.UnpivotOtherColumns(#"Valor reemplazado4", {"Concepto", "Column2"}, "Atributo", "Valor"),
    #"Personalizada agregada1" = Table.AddColumn(#"Otras columnas con anulación de dinamización", "Trimestre", each if [Column2] = "T1" then "I"
else if [Column2] = "T2" then "II"
else if [Column2] = "T3" then "III"
else if [Column2] = "T4" then "IV"
else ""),
    #"Columnas reordenadas" = Table.ReorderColumns(#"Personalizada agregada1",{"Concepto", "Trimestre", "Column2", "Atributo", "Valor"}),
    #"Columnas quitadas" = Table.RemoveColumns(#"Columnas reordenadas",{"Column2"}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas quitadas",{{"Concepto", "Año"}, {"Atributo", "Concepto"}}),
    #"Personalizada agregada2" = Table.AddColumn(#"Columnas con nombre cambiado", "Pais", each "Mexíco"),
    #"Personalizada agregada3" = Table.AddColumn(#"Personalizada agregada2", "ID", each [Año] & "_" & [Trimestre]),
    #"Columnas reordenadas1" = Table.ReorderColumns(#"Personalizada agregada3",{"Año", "Trimestre", "ID", "Concepto", "Valor", "Pais"}),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columnas reordenadas1",{{"ID", type text}, {"Trimestre", type text}, {"Año", Int64.Type}})
in
    #"Tipo cambiado1"
