let
    Origen = Folder.Files(#"RUTA (2)"),
    #"Filas filtradas1" = Table.SelectRows(Origen, each not Text.StartsWith([Extension], "~")),
    #"Filas filtradas" = Table.SelectRows(#"Filas filtradas1", each ([Extension] = ".xlsx") and ([Name] = "Pob_Ocupada_Mexico_2005_2024.xlsx")),
    #"Otras columnas quitadas" = Table.SelectColumns(#"Filas filtradas",{"Content", "Name"}),
    #"Personalizada agregada" = Table.AddColumn(#"Otras columnas quitadas", "Personalizado", each Excel.Workbook([Content],true)),
    #"Otras columnas quitadas1" = Table.SelectColumns(#"Personalizada agregada",{"Personalizado"}),
    #"Se expandió Personalizado" = Table.ExpandTableColumn(#"Otras columnas quitadas1", "Personalizado", {"Name", "Data", "Item", "Kind", "Hidden"}, {"Name", "Data", "Item", "Kind", "Hidden"}),
    #"Otras columnas quitadas2" = Table.SelectColumns(#"Se expandió Personalizado",{"Data"}),
    #"Se expandió Data" = Table.ExpandTableColumn(#"Otras columnas quitadas2", "Data", {"Población ocupada", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19"}, {"Población ocupada", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19"}),
    #"Filas superiores quitadas" = Table.Skip(#"Se expandió Data",4),
    #"Filas filtradas3" = Table.SelectRows(#"Filas superiores quitadas", each ([Column2] <> null and [Column2] <> "")),
    #"Encabezados promovidos" = Table.PromoteHeaders(#"Filas filtradas3", [PromoteAllScalars=true]),
    #"Otras columnas con anulación de dinamización" = Table.UnpivotOtherColumns(#"Encabezados promovidos", {""}, "Atributo", "Valor"),
    #"Dividir columna por delimitador" = Table.SplitColumn(#"Otras columnas con anulación de dinamización", "", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, true), {".1", ".2"}),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Dividir columna por delimitador",{{".1", type text}, {".2", Int64.Type}}),
    #"Personalizada agregada1" = Table.AddColumn(#"Tipo cambiado", "Trimestre", each if [#".1"] = "Primer trimestre del" then "I" else if [#".1"] = "Segundo trimestre del" then "II" else if [#".1"] = "Tercer trimestre del" then "III" else if [#".1"] = "Cuarto trimestre del" then "IV" else ""),
    #"Columnas reordenadas" = Table.ReorderColumns(#"Personalizada agregada1",{".1", ".2", "Trimestre", "Atributo", "Valor"}),
    #"Columnas quitadas" = Table.RemoveColumns(#"Columnas reordenadas",{".1"}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas quitadas",{{".2", "Año"}}),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Año", type text}}),
    #"Personalizada agregada3" = Table.AddColumn(#"Tipo cambiado1", "ID", each [Año] & "_" & [Trimestre]),
    #"Personalizada agregada2" = Table.AddColumn(#"Personalizada agregada3", "Pais", each "Mexíco"),
    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Personalizada agregada2",{{"Atributo", "Concepto"}}),
    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columnas con nombre cambiado1",{{"Año", Int64.Type}, {"Trimestre", type text}, {"Valor", type number}, {"ID", type text}, {"Pais", type text}})
in
    #"Tipo cambiado2"
